esphome:
  name: matrix-display
  friendly_name: Matrix Display
  libraries:
    - Wire
    - SPI
    - Adafruit BusIO
    - Adafruit GFX Library
    - ESP32 HUB75 LED MATRIX PANEL DMA Display
    - https://github.com/acvigue/libwebp

external_components:
  - source: https://github.com/carmichaeldylan-cdpro/ESPHome-HomeAssistant-Matrix@main
    components: smartmatrix


mqtt:
  broker: MQTT_HOST-OR-HOME_ASSISTANT_MQTT_HOST
  username: mqtt
  password: !secret mqtt_password

# Used for ESP32
esp32:
  board: esp32dev
  framework:
    type: arduino

# Enable logging
logger:
  level: DEBUG

# Enable Home Assistant API
display:
  - platform: smartmatrix
    id: matrix_display
    width: 64
    height: 32
    brightness: 255  # Initial brightness

number:
  - platform: smartmatrix
    name: "Matrix Brightness"
    id: matrix_brightness  # Changed to avoid conflict with display ID
    matrix_id: matrix_display  # Now matches the display's ID
    min_value: 0
    max_value: 255
    step: 1
    mode: SLIDER
    initial_value: 255

text_sensor:
  - platform: template
    name: "Device ID"
    id: device_identifier

