name: CI

on:
  push:
    branches: [main]

jobs:
  build:
    name: Building ${{ matrix.file }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        file:
          - smartmatrix.yaml
          - smartmatrix_trinity.yaml
    steps:
      - name: Checkout source code
        uses: actions/checkout@v2
      
      - name: Build ESPHome firmware
        id: esphome-build
        uses: esphome/build-action@v1.5.2
        with:
          yaml_file: ${{ matrix.file }}
      
      - uses: frabert/replace-string-action@v2
        id: replacer
        with:
          pattern: '(.*)(\.yaml)'
          string: ${{ matrix.file }}
          replace-with: '$1.bin'
      
      - name: Rename firmware image to match yaml
        run: |
          SOURCE_FILE=${{ matrix.file }}
          OUTPUT_FILE=${SOURCE_FILE/yaml/bin}
          echo $OUTPUT_FILE
          mkdir firmware && mv "${{ steps.esphome-build.outputs.name }}/${{ steps.esphome-build.outputs.name }}.bin" firmware/$OUTPUT_FILE

      - uses: actions/upload-artifact@v3.1.2
        with:
          name: firmware
          path: firmware

  release:
    runs-on: ubuntu-latest
    needs: build
    if: success() || failure()
    steps:
      - name: Checkout source code
        uses: actions/checkout@v2
      
      - name: Download reports' artifacts
        uses: actions/download-artifact@v3
        with:
          path: firmware
          
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: true
          prerelease: false
      
      - name: Upload Release Assets
        id: upload-release-assets
        uses: dwenegar/upload-release-assets@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          release_id: ${{ steps.create_release.outputs.id }}
          assets_path: firmware
